version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules
    command: sh -c "npm install && npm run build && node dist/index.js"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    command: sh -c "npm install && npm run build && npm run preview"
    depends_on:
      - backend

volumes:
  node_modules_backend:
  node_modules_frontend: