services:
  - type: web
    name: quiz-app-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_PATH
        value: ./database.sqlite
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /api/health
